[package]
name = "scientists_toolbox"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[dependencies]
wasm-bindgen = "0.2.80"
yew = "0.19.3"
yew-router = "0.16.0"
approx = "0.5.1"
assert_approx_eq = "1.1.0"