[tasks.dev]
command = "trunk"
args = ["build"]
workspace = false

[tasks.watch-dev]
command = "trunk"
args = ["serve"]
workspace = false

[tasks.release]
command = "trunk"
args = ["build", "--release"]
workspace = false

[tasks.tailwind-dev]
command = "npx"
args = ["tailwindcss", "-c", "./tailwind.config.js", "-o", "./index.css"]

[tasks.watch-tailwind-dev]
command = "npx"
args = ["tailwindcss", "-c", "./tailwind.config.js", "-o", "./index.css", "--watch"]

[tasks.tailwind-release]
command = "npx"
args = ["tailwindcss", "-c", "./tailwind.config.js", "-o", "./index.css", "--minify"]