[tasks.dev]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-dir", "./www/lib/", "--no-typescript", "--dev"]
workspace = false

[tasks.watch-dev]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-dir", "./www/lib/", "--no-typescript", "--dev"]
watch = { watch = ["./src"] }

[tasks.release]
command = "wasm-pack"
args = ["build", "--target", "web", "--out-dir", "./www/lib/", "--no-typescript", "--release"]

