[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.check-format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--fix"]

[tasks.check-clippy]
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]

[tasks.post-build]
command = "npm"
args = ["run", "post-build"]

[tasks.watch-post-build]
command = "npm"
args = ["run", "post-build"]
watch = true

[tasks.app-build-dev]
command = "trunk"
args = ["build"]
workspace = false

[tasks.watch-serve-dev]
command = "trunk"
args = ["serve", "--address", "0.0.0.0"]
workspace = false

[tasks.app-build-release]
command = "trunk"
args = ["build", "--release", "--public-url", "scientists-toolbox"]
workspace = false

[tasks.tailwind-dev]
command = "npx"
args = ["tailwindcss", "-c", "./tailwind.config.js", "-o", "./index.css"]

[tasks.watch-tailwind-dev]
command = "npx"
args = ["tailwindcss", "-c", "./tailwind.config.js", "-o", "./index.css", "--watch"]

[tasks.tailwind-release]
command = "npx"
args = ["tailwindcss", "-c", "./tailwind.config.js", "-o", "./index.css", "--minify"]

[tasks.test-dev]
command = "cargo"
args = ["test"]

[tasks.watch-test-dev]
dependencies = [
    "test-dev"
]
watch = true

[tasks.test-release]
command = "cargo"
args = ["test", "--release"]

[tasks.watch]
run_task = { name = [
    "watch-serve-dev",
    "watch-tailwind-dev",
    "watch-post-build"
    ], parallel = true }

[tasks.dev]
dependencies = [
    "format",
    "clippy",
    "tailwind-dev",
    "app-build-dev",
    "post-build",
    "test-dev"
]

[tasks.release]
dependencies = [
    "check-format",
    "check-clippy",
    "tailwind-release",
    "app-build-release",
    "post-build",
    "test-release",
]
