name: Build

on:
  workflow_call:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: NPM Install
      run: |
        npm install
      
    - name: Add target
      run: |
        rustup target add wasm32-unknown-unknown    
        
    - name: Install wasm-pack 
      uses: baptiste0928/cargo-install@v1.3.0
      with:
        crate: wasm-pack
        
    - name: Install trunk
      uses: baptiste0928/cargo-install@v1.3.0
      with:
        crate: trunk
        
    - name: Install cargo-make
      uses: baptiste0928/cargo-install@v1.3.0
      with:
        crate: cargo-make
        args: --debug
        
    - name: Run CI
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: release
      env: { CARGO_MAKE_RUN_CODECOV: true }
    
    - uses: actions/checkout@master
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "dist/index.html"
        target: "dist/404.html"
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: build
        path: dist

    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: dist


