name: Release Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: NPM Install
      run: |
        npm install
    
    - name: Install Trunk 
      run: |
        cargo install --locked trunk
    
    - name: Install Cargo Generate
      run: |
        cargo install cargo-generate
    
    - name: Install WASM Pack 
      run: |
        cargo install wasm-pack
    
    - name: Install cargo-make
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug cargo-make
        
    - name: Run CI
      uses: actions-rs/cargo@v1
      with:
        command: make
        args: release
      env: { CARGO_MAKE_RUN_CODECOV: true }
    
